"""Instruments tracked in Phase 1 (FEMA + RBI, Income Tax, SEBI). Adding a regulator means entries here plus an adapter.

official_url is the page the seeder/self-check re-scrapes for the regulator's own consolidated text.
`rbi_md_id` identifies the Master Direction on rbi.org.in; the seeder uses the HTML detail page (cleaner than the PDF).
"""
from __future__ import annotations

# SEBI keeps one consolidated "[Last amended on <date>]" page per Act / Regulation, and mints a new URL every time
# it republishes one. `seed.match` is therefore the stable key: the seeder re-finds the current page on the Legal
# listing and `official_url` is only a fallback. Every other consolidated Regulation on that listing is registered
# automatically at discovery time (adapters/sebi.py -> pipeline._ensure_instrument).
SEBI_INSTRUMENTS: list[dict] = [
    {
        "slug": "sebi-act-1992",
        "short_code": "SEBI-ACT",
        "title": "Securities and Exchange Board of India Act, 1992",
        "kind": "act",
        "regulator": "SEBI",
        "official_url": "https://www.sebi.gov.in/legal/acts/jan-1992/securities-and-exchange-board-of-india-act-1992-as-amended-by-the-finance-act-2021-13-of-2021-w-e-f-april-1-2021-_3.html",
        "seed": {"adapter": "sebi", "listing": "acts", "match": r"^Securities and Exchange Board of India Act,?\s*1992", "style": "sebi"},
    },
    {
        "slug": "scra-1956",
        "short_code": "SCRA",
        "title": "Securities Contracts (Regulation) Act, 1956",
        "kind": "act",
        "regulator": "SEBI",
        "official_url": "https://www.sebi.gov.in/legal/acts/apr-2021/securities-contracts-regulation-act-1956-as-amended-by-the-finance-act-2021-13-of-2021-w-e-f-april-1-2021-_49750.html",
        "seed": {"adapter": "sebi", "listing": "acts", "match": r"^Securities Contracts \(Regulation\) Act,?\s*1956", "style": "sebi"},
    },
    {
        "slug": "depositories-act-1996",
        "short_code": "DEP-ACT",
        "title": "Depositories Act, 1996",
        "kind": "act",
        "regulator": "SEBI",
        "official_url": "https://www.sebi.gov.in/legal/acts/sep-1995/depositories-act-1996-as-amended-by-the-international-financial-services-centres-authority-act-2019-w-e-f-october-01-2020-_1.html",
        "seed": {"adapter": "sebi", "listing": "acts", "match": r"^Depositories Act,?\s*1996", "style": "sebi"},
    },
    {
        "slug": "sebi-lodr-2015",
        "short_code": "SEBI-LODR",
        "title": "Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015",
        "kind": "regulations",
        "regulator": "SEBI",
        "official_url": "https://www.sebi.gov.in/legal/regulations/jul-2026/securities-and-exchange-board-of-india-listing-obligations-and-disclosure-requirements-regulations-2015-last-amended-on-july-14-2026-_102974.html",
        "seed": {"adapter": "sebi", "listing": "regulations", "match": r"Listing Obligations and Disclosure Requirements", "style": "sebi"},
    },
    {
        "slug": "sebi-icdr-2018",
        "short_code": "SEBI-ICDR",
        "title": "Securities and Exchange Board of India (Issue of Capital and Disclosure Requirements) Regulations, 2018",
        "kind": "regulations",
        "regulator": "SEBI",
        "official_url": "https://www.sebi.gov.in/legal/regulations/mar-2026/securities-and-exchange-board-of-india-issue-of-capital-and-disclosure-requirements-regulations-2018-last-amended-on-march-21-2026-_100581.html",
        "seed": {"adapter": "sebi", "listing": "regulations", "match": r"Issue of Capital and Disclosure Requirements", "style": "sebi"},
    },
    {
        "slug": "sebi-sast-2011",
        "short_code": "SEBI-SAST",
        "title": "Securities and Exchange Board of India (Substantial Acquisition of Shares and Takeovers) Regulations, 2011",
        "kind": "regulations",
        "regulator": "SEBI",
        "official_url": "https://www.sebi.gov.in/legal/regulations/dec-2025/securities-and-exchange-board-of-india-substantial-acquisition-of-shares-and-takeovers-regulations-2011-last-amended-on-december-5-2025-_98643.html",
        "seed": {"adapter": "sebi", "listing": "regulations", "match": r"Substantial Acquisition of Shares and Takeovers", "style": "sebi"},
    },
    {
        "slug": "sebi-pit-2015",
        "short_code": "SEBI-PIT",
        "title": "Securities and Exchange Board of India (Prohibition of Insider Trading) Regulations, 2015",
        "kind": "regulations",
        "regulator": "SEBI",
        "official_url": "https://www.sebi.gov.in/legal/regulations/mar-2025/securities-and-exchange-board-of-india-prohibition-of-insider-trading-regulations-2015-last-amended-on-march-12-2025-_92672.html",
        "seed": {"adapter": "sebi", "listing": "regulations", "match": r"Prohibition of Insider Trading", "style": "sebi"},
    },
    {
        # SEBI recast the Mutual Funds Regulations, 1996 as the (Mutual Funds) Regulations, 2026; the listing keeps
        # only the current text, so the slug carries no year and `match` follows whichever is published.
        "slug": "sebi-mutual-funds",
        "short_code": "SEBI-MF",
        "title": "Securities and Exchange Board of India (Mutual Funds) Regulations",
        "kind": "regulations",
        "regulator": "SEBI",
        "official_url": "https://www.sebi.gov.in/legal/regulations/jul-2026/securities-and-exchange-board-of-india-mutual-funds-regulations-2026-last-amended-on-july-7-2026-_102780.html",
        "seed": {"adapter": "sebi", "listing": "regulations", "match": r"\(Mutual Funds\)\s*Regulations", "style": "sebi"},
    },
    {
        "slug": "sebi-aif-2012",
        "short_code": "SEBI-AIF",
        "title": "Securities and Exchange Board of India (Alternative Investment Funds) Regulations, 2012",
        "kind": "regulations",
        "regulator": "SEBI",
        "official_url": "https://www.sebi.gov.in/legal/regulations/apr-2026/securities-and-exchange-board-of-india-alternative-investment-funds-regulations-2012-last-amended-on-april-18-2026-_101019.html",
        "seed": {"adapter": "sebi", "listing": "regulations", "match": r"\(Alternative Investment Funds", "style": "sebi"},
    },
    {
        "slug": "sebi-portfolio-managers-2020",
        "short_code": "SEBI-PMS",
        "title": "Securities and Exchange Board of India (Portfolio Managers) Regulations, 2020",
        "kind": "regulations",
        "regulator": "SEBI",
        "official_url": "https://www.sebi.gov.in/legal/regulations/sep-2025/securities-and-exchange-board-of-india-portfolio-managers-regulations-2020-last-amended-on-september-03-2025-_96560.html",
        "seed": {"adapter": "sebi", "listing": "regulations", "match": r"\(Portfolio Managers\)\s*Regulations", "style": "sebi"},
    },
    {
        "slug": "sebi-buyback-2018",
        "short_code": "SEBI-BUYBACK",
        "title": "Securities and Exchange Board of India (Buy-Back of Securities) Regulations, 2018",
        "kind": "regulations",
        "regulator": "SEBI",
        "official_url": "https://www.sebi.gov.in/legal/regulations/jul-2026/securities-and-exchange-board-of-india-buy-back-of-securities-regulations-2018-last-amended-on-july-6-2026-_103042.html",
        "seed": {"adapter": "sebi", "listing": "regulations", "match": r"Buy-?Back of Securities", "style": "sebi"},
    },
    {
        "slug": "sebi-delisting-2021",
        "short_code": "SEBI-DELISTING",
        "title": "Securities and Exchange Board of India (Delisting of Equity Shares) Regulations, 2021",
        "kind": "regulations",
        "regulator": "SEBI",
        "official_url": "https://www.sebi.gov.in/legal/regulations/sep-2025/securities-and-exchange-board-of-india-delisting-of-equity-shares-regulations-2021-last-amended-on-september-3-2025-_96548.html",
        "seed": {"adapter": "sebi", "listing": "regulations", "match": r"Delisting of Equity Shares", "style": "sebi"},
    },
]

CBDT_INSTRUMENTS: list[dict] = [
    {
        "slug": "ita-1961",
        "short_code": "ITA-1961",
        "title": "Income-tax Act, 1961",
        "kind": "act",
        "regulator": "CBDT",
        "official_url": "https://www.incometaxindia.gov.in/income-tax-act",
        "seed": {"adapter": "cbdt_act", "match": "Income-tax Act, 1961", "page": "/income-tax-act", "style": "act"},
    },
    {
        "slug": "ita-2025",
        "short_code": "ITA-2025",
        "title": "Income-tax Act, 2025",
        "kind": "act",
        "regulator": "CBDT",
        "official_url": "https://www.incometaxindia.gov.in/income-tax-act-202511",
        "seed": {"adapter": "cbdt_act", "match": "Income-tax Act, 2025", "page": "/income-tax-act-202511", "style": "act"},
    },
    {
        "slug": "itr-1962",
        "short_code": "ITR-1962",
        "title": "Income-tax Rules, 1962",
        "kind": "rules",
        "regulator": "CBDT",
        "official_url": "https://www.incometaxindia.gov.in/income-tax-rules",
        "seed": {"adapter": "cbdt_act", "kind": "rules", "match": "Income-tax Rules, 1962", "page": "/income-tax-rules", "style": "regulations"},
    },
    {
        "slug": "itr-2026",
        "short_code": "ITR-2026",
        "title": "Income-tax Rules, 2026",
        "kind": "rules",
        "regulator": "CBDT",
        "official_url": "https://www.incometaxindia.gov.in/income-tax-rule-2026",
        "seed": {"adapter": "cbdt_act", "kind": "rules", "match": "Income-tax Rules, 2026", "page": "/income-tax-rule-2026", "style": "regulations"},
    },
]

PHASE1_INSTRUMENTS: list[dict] = SEBI_INSTRUMENTS + CBDT_INSTRUMENTS + [
    {
        "slug": "fema-1999",
        "short_code": "FEMA",
        "title": "Foreign Exchange Management Act, 1999",
        "kind": "act",
        "regulator": "DEA",
        # RBI's Act page links to the Government's India Code copy; the seeder follows that link.
        "official_url": "https://www.rbi.org.in/scripts/Act.aspx",
        "seed": {"adapter": "rbi_fema_act", "style": "act", "text_url": None},
    },
    {
        "slug": "md-ecb",
        "short_code": "MD-ECB",
        "title": "Master Direction - External Commercial Borrowings, Trade Credits and Structured Obligations",
        "kind": "master_direction",
        "regulator": "RBI",
        "official_url": "https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=11510",
        "seed": {"adapter": "rbi_master_directions", "rbi_md_id": 11510, "style": "master_direction"},
    },
    {
        "slug": "md-overseas-investment",
        "short_code": "MD-OI",
        "title": "Master Direction - Overseas Investment",
        "kind": "master_direction",
        "regulator": "RBI",
        "official_url": "https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=12710",
        "seed": {"adapter": "rbi_master_directions", "rbi_md_id": 12710, "style": "master_direction"},
    },
    {
        "slug": "md-lrs",
        "short_code": "MD-LRS",
        "title": "Master Direction - Liberalised Remittance Scheme (LRS)",
        "kind": "master_direction",
        "regulator": "RBI",
        "official_url": "https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=10192",
        "seed": {"adapter": "rbi_master_directions", "rbi_md_id": 10192, "style": "master_direction"},
    },
    {
        "slug": "md-import-goods-services",
        "short_code": "MD-IMPORT",
        "title": "Master Direction - Import of Goods and Services",
        "kind": "master_direction",
        "regulator": "RBI",
        "official_url": "https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=10201",
        "seed": {"adapter": "rbi_master_directions", "rbi_md_id": 10201, "style": "master_direction"},
    },
    {
        "slug": "md-export-goods-services",
        "short_code": "MD-EXPORT",
        "title": "Master Direction - Export of Goods and Services",
        "kind": "master_direction",
        "regulator": "RBI",
        "official_url": "https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=10395",
        "seed": {"adapter": "rbi_master_directions", "rbi_md_id": 10395, "style": "master_direction"},
    },
    {
        "slug": "md-inr-borrowing-lending-nri",
        "short_code": "MD-INR-BL",
        "title": "Master Direction - Borrowing and Lending transactions in Indian Rupee between Persons Resident in India and Non-Resident Indians / Persons of Indian Origin",
        "kind": "master_direction",
        "regulator": "RBI",
        "official_url": "https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=10191",
        "seed": {"adapter": "rbi_master_directions", "rbi_md_id": 10191, "style": "master_direction"},
    },
    # GST (CBIC). Text comes from the section-wise "as amended" pages of CBIC's tax-information portal
    # (see adapters/cbic_gst.py); act_id / rule_id are the portal's identifiers for taxId 1000001 (GST).
    {
        "slug": "cgst-act-2017",
        "short_code": "CGST",
        "title": "Central Goods and Services Tax Act, 2017",
        "kind": "act",
        "regulator": "CBIC",
        "official_url": "https://taxinformation.cbic.gov.in/api/cbic-act-section-msts/findByActId/1000006",
        "seed": {"adapter": "cbic_gst", "style": "act", "act_id": 1000006},
    },
    {
        "slug": "igst-act-2017",
        "short_code": "IGST",
        "title": "Integrated Goods and Services Tax Act, 2017",
        "kind": "act",
        "regulator": "CBIC",
        "official_url": "https://taxinformation.cbic.gov.in/api/cbic-act-section-msts/findByActId/1000015",
        "seed": {"adapter": "cbic_gst", "style": "act", "act_id": 1000015},
    },
    {
        "slug": "utgst-act-2017",
        "short_code": "UTGST",
        "title": "Union Territory Goods and Services Tax Act, 2017",
        "kind": "act",
        "regulator": "CBIC",
        "official_url": "https://taxinformation.cbic.gov.in/api/cbic-act-section-msts/findByActId/1000016",
        "seed": {"adapter": "cbic_gst", "style": "act", "act_id": 1000016},
    },
    {
        "slug": "gst-compensation-act-2017",
        "short_code": "GST-COMP",
        "title": "Goods and Services Tax (Compensation to States) Act, 2017",
        "kind": "act",
        "regulator": "CBIC",
        "official_url": "https://taxinformation.cbic.gov.in/api/cbic-act-section-msts/findByActId/1000013",
        "seed": {"adapter": "cbic_gst", "style": "act", "act_id": 1000013},
    },
    {
        "slug": "cgst-rules-2017",
        "short_code": "CGST-RULES",
        "title": "Central Goods and Services Tax Rules, 2017",
        "kind": "rules",
        "regulator": "CBIC",
        "official_url": "https://taxinformation.cbic.gov.in/api/cbic-rule-section-msts/findSectionByRuleId/1000006",
        "seed": {"adapter": "cbic_gst", "style": "regulations", "rule_id": 1000006},
    },
]

# Extra Master Directions are appended at seed time from the RBI listing when their title matches these patterns,
# so new FEMA Master Directions are picked up without a code change.
FEMA_MD_TITLE_PATTERNS = [
    r"Foreign Exchange",
    r"FEMA",
    r"External Commercial",
    r"Remittance",
    r"Overseas Investment",
    r"Export of Goods",
    r"Import of Goods",
    r"Non-Resident",
    r"Deposits and Accounts",
    r"Money Changing",
    r"Compounding of Contraventions",
    r"Reporting under Foreign Exchange",
    r"Establishment of Branch",
    r"Acquisition and Transfer of Immovable",
    r"Insurance",
    r"Other Remittance Facilities",
    r"Vostro",
    r"Risk Management and Inter-Bank",
    r"Guarantee",
    r"Borrowing and Lending",
    r"Direct Investment by Residents",
    r"Foreign Investment in India",
]
