"""Instruments tracked in Phase 1 (FEMA + RBI). Adding a regulator later means adding entries here plus an adapter.

official_url is the page the seeder/self-check re-scrapes for the regulator's own consolidated text.
`rbi_md_id` identifies the Master Direction on rbi.org.in; the seeder uses the HTML detail page (cleaner than the PDF).
"""
from __future__ import annotations

CBDT_INSTRUMENTS: list[dict] = [
    {
        "slug": "ita-1961",
        "short_code": "ITA-1961",
        "title": "Income-tax Act, 1961",
        "kind": "act",
        "regulator": "CBDT",
        "official_url": "https://www.incometaxindia.gov.in/income-tax-act",
        "seed": {"adapter": "cbdt_act", "match": "Income-tax Act, 1961", "page": "/income-tax-act", "style": "act"},
    },
    {
        "slug": "ita-2025",
        "short_code": "ITA-2025",
        "title": "Income-tax Act, 2025",
        "kind": "act",
        "regulator": "CBDT",
        "official_url": "https://www.incometaxindia.gov.in/income-tax-act-202511",
        "seed": {"adapter": "cbdt_act", "match": "Income-tax Act, 2025", "page": "/income-tax-act-202511", "style": "act"},
    },
    {
        "slug": "itr-1962",
        "short_code": "ITR-1962",
        "title": "Income-tax Rules, 1962",
        "kind": "rules",
        "regulator": "CBDT",
        "official_url": "https://www.incometaxindia.gov.in/income-tax-rules",
        "seed": {"adapter": "cbdt_act", "kind": "rules", "match": "Income-tax Rules, 1962", "page": "/income-tax-rules", "style": "regulations"},
    },
    {
        "slug": "itr-2026",
        "short_code": "ITR-2026",
        "title": "Income-tax Rules, 2026",
        "kind": "rules",
        "regulator": "CBDT",
        "official_url": "https://www.incometaxindia.gov.in/income-tax-rule-2026",
        "seed": {"adapter": "cbdt_act", "kind": "rules", "match": "Income-tax Rules, 2026", "page": "/income-tax-rule-2026", "style": "regulations"},
    },
]

PHASE1_INSTRUMENTS: list[dict] = CBDT_INSTRUMENTS + [
    {
        "slug": "fema-1999",
        "short_code": "FEMA",
        "title": "Foreign Exchange Management Act, 1999",
        "kind": "act",
        "regulator": "DEA",
        # RBI's Act page links to the Government's India Code copy; the seeder follows that link.
        "official_url": "https://www.rbi.org.in/scripts/Act.aspx",
        "seed": {"adapter": "rbi_fema_act", "style": "act", "text_url": None},
    },
    {
        "slug": "md-ecb",
        "short_code": "MD-ECB",
        "title": "Master Direction - External Commercial Borrowings, Trade Credits and Structured Obligations",
        "kind": "master_direction",
        "regulator": "RBI",
        "official_url": "https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=11510",
        "seed": {"adapter": "rbi_master_directions", "rbi_md_id": 11510, "style": "master_direction"},
    },
    {
        "slug": "md-overseas-investment",
        "short_code": "MD-OI",
        "title": "Master Direction - Overseas Investment",
        "kind": "master_direction",
        "regulator": "RBI",
        "official_url": "https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=12710",
        "seed": {"adapter": "rbi_master_directions", "rbi_md_id": 12710, "style": "master_direction"},
    },
    {
        "slug": "md-lrs",
        "short_code": "MD-LRS",
        "title": "Master Direction - Liberalised Remittance Scheme (LRS)",
        "kind": "master_direction",
        "regulator": "RBI",
        "official_url": "https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=10192",
        "seed": {"adapter": "rbi_master_directions", "rbi_md_id": 10192, "style": "master_direction"},
    },
    {
        "slug": "md-import-goods-services",
        "short_code": "MD-IMPORT",
        "title": "Master Direction - Import of Goods and Services",
        "kind": "master_direction",
        "regulator": "RBI",
        "official_url": "https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=10201",
        "seed": {"adapter": "rbi_master_directions", "rbi_md_id": 10201, "style": "master_direction"},
    },
    {
        "slug": "md-export-goods-services",
        "short_code": "MD-EXPORT",
        "title": "Master Direction - Export of Goods and Services",
        "kind": "master_direction",
        "regulator": "RBI",
        "official_url": "https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=10395",
        "seed": {"adapter": "rbi_master_directions", "rbi_md_id": 10395, "style": "master_direction"},
    },
    {
        "slug": "md-inr-borrowing-lending-nri",
        "short_code": "MD-INR-BL",
        "title": "Master Direction - Borrowing and Lending transactions in Indian Rupee between Persons Resident in India and Non-Resident Indians / Persons of Indian Origin",
        "kind": "master_direction",
        "regulator": "RBI",
        "official_url": "https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=10191",
        "seed": {"adapter": "rbi_master_directions", "rbi_md_id": 10191, "style": "master_direction"},
    },
    # GST (CBIC). Text comes from the section-wise "as amended" pages of CBIC's tax-information portal
    # (see adapters/cbic_gst.py); act_id / rule_id are the portal's identifiers for taxId 1000001 (GST).
    {
        "slug": "cgst-act-2017",
        "short_code": "CGST",
        "title": "Central Goods and Services Tax Act, 2017",
        "kind": "act",
        "regulator": "CBIC",
        "official_url": "https://taxinformation.cbic.gov.in/api/cbic-act-section-msts/findByActId/1000006",
        "seed": {"adapter": "cbic_gst", "style": "act", "act_id": 1000006},
    },
    {
        "slug": "igst-act-2017",
        "short_code": "IGST",
        "title": "Integrated Goods and Services Tax Act, 2017",
        "kind": "act",
        "regulator": "CBIC",
        "official_url": "https://taxinformation.cbic.gov.in/api/cbic-act-section-msts/findByActId/1000015",
        "seed": {"adapter": "cbic_gst", "style": "act", "act_id": 1000015},
    },
    {
        "slug": "utgst-act-2017",
        "short_code": "UTGST",
        "title": "Union Territory Goods and Services Tax Act, 2017",
        "kind": "act",
        "regulator": "CBIC",
        "official_url": "https://taxinformation.cbic.gov.in/api/cbic-act-section-msts/findByActId/1000016",
        "seed": {"adapter": "cbic_gst", "style": "act", "act_id": 1000016},
    },
    {
        "slug": "gst-compensation-act-2017",
        "short_code": "GST-COMP",
        "title": "Goods and Services Tax (Compensation to States) Act, 2017",
        "kind": "act",
        "regulator": "CBIC",
        "official_url": "https://taxinformation.cbic.gov.in/api/cbic-act-section-msts/findByActId/1000013",
        "seed": {"adapter": "cbic_gst", "style": "act", "act_id": 1000013},
    },
    {
        "slug": "cgst-rules-2017",
        "short_code": "CGST-RULES",
        "title": "Central Goods and Services Tax Rules, 2017",
        "kind": "rules",
        "regulator": "CBIC",
        "official_url": "https://taxinformation.cbic.gov.in/api/cbic-rule-section-msts/findSectionByRuleId/1000006",
        "seed": {"adapter": "cbic_gst", "style": "regulations", "rule_id": 1000006},
    },
]

# Extra Master Directions are appended at seed time from the RBI listing when their title matches these patterns,
# so new FEMA Master Directions are picked up without a code change.
FEMA_MD_TITLE_PATTERNS = [
    r"Foreign Exchange",
    r"FEMA",
    r"External Commercial",
    r"Remittance",
    r"Overseas Investment",
    r"Export of Goods",
    r"Import of Goods",
    r"Non-Resident",
    r"Deposits and Accounts",
    r"Money Changing",
    r"Compounding of Contraventions",
    r"Reporting under Foreign Exchange",
    r"Establishment of Branch",
    r"Acquisition and Transfer of Immovable",
    r"Insurance",
    r"Other Remittance Facilities",
    r"Vostro",
    r"Risk Management and Inter-Bank",
    r"Guarantee",
    r"Borrowing and Lending",
    r"Direct Investment by Residents",
    r"Foreign Investment in India",
]
